FROM nginx:latest
USER root
WORKDIR /home/

COPY /server/nginx/nginx.conf /etc/nginx/nginx.conf
COPY /server/miniserv.c /home/miniserv.c
COPY start.sh /home/start.sh
RUN apt-get update; \
    apt-get install -y gcc libfcgi-dev spawn-fcgi; \
    chmod +x start.sh

ENTRYPOINT bash start.sh
